language: php

php:
  - 5.3
  - 5.2
  - 5.4
  - 5.5

env:
  global:
    - DB_ENGINE=InnoDB
  matrix:
    - WP_VERSION=3.5
    - WP_VERSION=3.9
    - WP_VERSION=4.0.1
    - WP_VERSION=3.8
    - WP_VERSION=4.1.1
    - WP_VERSION=3.6
    - WP_VERSION=3.4
    - WP_VERSION=3.7
    - WP_VERSION=3.3
    - WP_VERSION=3.2

matrix:
  include:
    - php: 5.3
      env: DB_ENGINE=MyISAM DB_CHARSET=latin1
    - php: 5.4
      env: PLUGINS=akismet.3.0.4:jetpack.3.3:wordpress-seo.1.7.1:wordfence.5.3.4:contact-form-7.4.0.3:google-sitemap-generator.4.0.8
  allow_failures:
    - php: 5.2
      env: WP_VERSION=3.5
    - php: 5.2
      env: WP_VERSION=3.6
    - php: 5.2
      env: WP_VERSION=3.7

addons:
  hosts:
    - wpti.dev

before_script:
  - tests/integration-environment/composer-update.sh
  - mysql -e 'create database wordpress;'
  - cd db
  - $TRAVIS_BUILD_DIR/vendor/bin/ruckus.php db:migrate
  - cd $TRAVIS_BUILD_DIR
  - tests/integration-environment/create.sh
  - cd $TRAVIS_BUILD_DIR/tests/mocha
  - npm install
  - cd $TRAVIS_BUILD_DIR
  - export PATH=$PATH:$TRAVIS_BUILD_DIR/tests/mocha/node_modules/.bin/:$TRAVIS_BUILD_DIR/tests/integration-environment/

script:
  - vendor/bin/phpunit-php52
  - cd $TRAVIS_BUILD_DIR/tests/mocha/test
  - mocha-casperjs --timeout=360000 0-plugin.js
  - restart.sh && mocha-casperjs answers-and-scales-1.js
  - restart.sh && mocha-casperjs answers-and-scales-2.js
  - restart.sh && mocha-casperjs diagrams.js
  - restart.sh && mocha-casperjs multiple-answers.js
  - restart.sh && mocha-casperjs page.js
  - restart.sh && mocha-casperjs questions.js
  - restart.sh && mocha-casperjs quick-edit.js
  - restart.sh && mocha-casperjs results-with-formulas.js
  - restart.sh && mocha-casperjs scale-aggregates.js
  - restart.sh && mocha-casperjs scores.js
  - restart.sh && mocha-casperjs shortcode.js
  - restart.sh && mocha-casperjs steps.js
  - restart.sh && mocha-casperjs taxonomies.js
  - restart.sh && mocha-casperjs test.js
  - restart.sh && mocha-casperjs y-passing.js
  - restart.sh && mocha-casperjs y-respondents-results.js
  - restart.sh && mocha-casperjs z-plugin.js

after_failure:
  - sudo free -ltm
  - cd $TRAVIS_BUILD_DIR/tests/mocha
  - ./debug-to-mail.sh a@ustimen.co 'Failed build dump' /tmp/*.dmp
  - ./debug-to-mail.sh a@ustimen.co 'Debug screenshots' /tmp/*.screen.png
